name: Sadiq Awosanmi
description: Sadiq Awosanmi. Software Engineer, Artist, Entrepreneur
markdown: kramdown
timezone: America/Toronto
url: https://sadiqawosanmi.com
author: Sadiq Awosanmi
excerpt_separator: <!--more-->

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 4
paginate_path: "/journal/p:num/"
